/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
   */
};

module.exports = sidebars;


// module.exports = {
//   docs: {
//     'Getting Started': [
//       'what-is-docsearch',
//       'how-does-it-work',
//       'who-can-apply',
//       'apply',
//     ],
//     'Adding DocSearch to your UI': ['dropdown', 'styling', 'behavior'],
//     'Requirements, tips, FAQ': [
//       'required-configuration',
//       'tips',
//       'faq',
//       'integrations',
//     ],
//     'Under the Hood': [
//       'scraper',
//       'inside-the-engine',
//       'config-file',
//       'how-do-we-build-an-index',
//       'run-your-own',
//     ],
//   },
// };